repos:
-   repo: local
    hooks:
    -   id: pandoc-build
        name: Build with Pandoc
        entry: /usr/bin/pandoc --standalone --from=markdown --to=html --include-in-header=header.html --output=index.html --css=style.css --metadata title="Notes on the TCHC"
        language: script
        always_run: true
        pass_filenames: false
