repos:
-   repo: local
    hooks:
    -   id: pandoc-build
        name: Build with Pandoc
        entry: /usr/bin/pandoc index.markdown -o index.html --css=style.css
        language: script
        always_run: true
        pass_filenames: false
