repos:
-   repo: local
    hooks:
    -   id: pandoc-build
        name: Build with Pandoc
        entry: /usr/bin/pandoc index.markdown --standalone --from=markdown --to=html --include-in-header=header.html --output=index.html --css=style.css
        language: script
        always_run: true
        pass_filenames: false
