repos:
-   repo: local
    hooks:
    -   id: pandoc-build
        name: Build with Pandoc
        entry: clubber/build
        language: script
        always_run: true
        pass_filenames: false
